### ISSUE TITLE
My world2screen return weird position 

### ISSUE THREAD

**Issue by Jerem584** [michel-pi/GameMath.Net#2]
-0,9842894 11 to matrix { {M11:-0,9842894 M12:-0,1765626 M13:-1,192148E-07 M14:0} {M21:-0,176426 M22:0,9835277 M23:0,03933312 M24:0} {M31:-0,006944642 M32:0,0387152 M33:-0,9992262 M34:0} {M41:13532,98 M42:74456,52 M43:84293,97 M44:1} }

And this return weird position ...

**Comment by Jerem584** [comment]
Only m13 is weird, but this return me the same position for all entity

**Comment by Jerem584** [comment]
Like entity position are différents between all entity but same position After w2s

**Comment by michel-pi** [comment]
there is nothing wrong with the matrix struct or the worldtoscreen function. your code is wrong or your viewmatrix is wrong

**Comment by Jerem584** [comment]
Yeah i know, can you give me a example of working matrix values?

**Comment by Jerem584** [comment]
{X = 960,5, Y = 539,5}
actorloc :[ -119872,4 - -113600 - 3967,251 ]   {X = -119872,4, Y = -113600, Z = 3967,251}{ {M11:-0,9615234 M12:0,2747233 M13:0,2677149 M14:0} {M21:0,06165699 M22:0,2157977 M23:0,9744896 M24:0} {M31:0,2677149 M32:0,9369946 M33:-0,2244331 M34:0} {M41:-126115,1 M42:-112958,2 M43:4042,123 M44:1} }
{X = 960,5029, Y = 539,5005}
actorloc :[ -124334,5 - -115947 - 3967,859 ]   {X = -124334,5, Y = -115947, Z = 3967,859}{ {M11:-0,9615234 M12:0,2747233 M13:0,2677149 M14:0} {M21:0,06165699 M22:0,2157977 M23:0,9744896 M24:0} {M31:0,2677149 M32:0,9369946 M33:-0,2244331 M34:0} {M41:-126115,1 M42:-112958,2 M43:4042,123 M44:1} }
{X = 960,5029, Y = 539,5005}
actorloc :[ -127939,1 - -110841,5 - 3841,01 ]   {X = -127939,1, Y = -110841,5, Z = 3841,01}{ {M11:-0,9615234 M12:0,2747233 M13:0,2677149 M14:0} {M21:0,06165699 M22:0,2157977 M23:0,9744896 M24:0} {M31:0,2677149 M32:0,9369946 M33:-0,2244331 M34:0} {M41:-126115,1 M42:-112958,2 M43:4042,123 M44:1} }
{X = 960,5031, Y = 539,5005}
actorloc :[ -128062,1 - -110506,9 - 3967,88 ]   {X = -128062,1, Y = -110506,9, Z = 3967,88}{ {M11:-0,9615234 M12:0,2747233 M13:0,2677149 M14:0} {M21:0,06165699 M22:0,2157977 M23:0,9744896 M24:0} {M31:0,2677149 M32:0,9369946 M33:-0,2244331 M34:0} {M41:-126115,1 M42:-112958,2 M43:4042,123 M44:1} }
{X = 960,5032, Y = 539,5005}

**Comment by michel-pi** [comment]
there is no "working" matrix valu. it depends on the context.
you coordinate pair is only x and y?

**Comment by Jerem584** [comment]
I have fix degrees but i cant seem to do working w2s with. So i decided to get viewmatrix and its all i have

**Comment by michel-pi** [comment]
doesnt change the fact that i can not help you to produce a correct matrix.
