### ISSUE TITLE
Ambiguous documentation

### ISSUE THREAD

**Issue by TylerBurnett** [michel-pi/GameMath.Net#3]
Hey there, I love this library and it has been a great help in creating my Aimbot. One thing I have trouble understanding is the comments around a lot of the functions. 

For example: 
```
        // <summary>
        /// Calculates the difference of two angles.
        /// </summary>
        /// <param name="pointOfView">The point of view.</param>
        /// <param name="angle_1">The first angle.</param>
        /// <param name="angle_2">The second angle.</param>
        /// <returns>Degree.</returns>
```

Does 'pointOfView' mean the players Vector3 position or his current Vector3 rotation?
Though 'angle_1' and 'angle_2' are quite self-explanatory, it would significantly help if this was put in a 3D context.

I know to a person that understands the math it may seem straight forward, but as a beginner, I'm finding myself scratching my head at what a large portion of these calculations do.

Besides this, I love the Library. It's super efficient and lightweight.

**Comment by michel-pi** [comment]
Hi,
the first parameter is your position (origin) + the height of your eyes, the second one is your view angle and the third the destination angle.

I myself just copy pasted and collected most of the functionality from the internet so i am not that good at this stuff either. For me, this is just a collection of those.

Also, the documentation is auto generated most of the time, hence not that useful.

Currently, for my aimbot, i use the GetFOV function:
`public static float GetFov(Vector3 angle, Vector3 src, Vector3 dst)`
which has to be called using your current view angle, your position (origin) + the height of your eyes and the position of the hitbox / bone / location you want to aim at.
This returns the angle difference in degrees.

You can ask more questions if you need to :)

**Comment by TylerBurnett** [comment]
Thank you, that FOV calc is a worlds better than my previous function.
