### ISSUE TITLE
ScreenToWorld Can be Done ? 

### ISSUE THREAD

**Issue by leftspace89** [michel-pi/GameMath.Net#4]
thanks for making this library public.
I don't know how to translate screen2d to world3d position (because of my math is not good).
if its possible can you add this one too. :)

**Comment by michel-pi** [comment]
i dont habe anything related to this flying around.
i made this repository to have a collection of methods i constantly use and i did not need to translate 2d into 3d coordinates so far.
i believe you can find something working on google and i would be happy if you can contribute it to this repository.
